### ISSUE TITLE
An issue with if(PEDANTIC) bb_tree.cpp

### ISSUE THREAD

**Issue by Majid-Khosh** [alberto-santini/maritime-vrp#3]

**Comment by Kaustav6422** [comment]
Were you able to solve this problem ? I am facing the same.

**Comment by soaringhigh** [comment]
Hi,
I face the same issues when compiling with clang++ and gcc. All the concert and cplex libraries are included (-lconcert -lilocplex -lcplex), and also the include paths specified properly. Still I struggle with the "undefined reference to `IloEnv::IloEnv()'". Anyone was able to fix this issue - seems like some pointer is not quite right, but I can't find it for days. Thanks!
